# Generated by Django 3.0.8 on 2020-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fb',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
