# Generated by Django 3.0.8 on 2020-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='product-7.jpg', null=True, upload_to=''),
        ),
    ]
