# Generated by Django 2.2.14 on 2020-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201003_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('HouseKeeping', 'HouseKeeping'), ('PestControl', 'PestControl'), ('Carpenter', 'Carpenter'), ('Milk', 'Milk'), ('Civil', 'Civil'), ('Newspaper', 'Newspaper')], max_length=200, null=True),
        ),
    ]
