# Generated by Django 2.2.14 on 2020-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201003_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='no-profile-pic-icon-27.jpg', null=True, upload_to=''),
        ),
    ]
