# Generated by Django 2.2.14 on 2020-10-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_vendor_timesbooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='LikedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Customer'),
        ),
    ]
