# Generated by Django 2.2.14 on 2020-10-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_vendor_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='LikedBy',
        ),
    ]
