# Generated by Django 2.2.14 on 2020-10-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_vendor_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='likedby',
            field=models.ManyToManyField(to='account.Customer'),
        ),
    ]
