# Generated by Django 2.2.14 on 2020-10-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_vendor_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='likedby',
        ),
        migrations.AddField(
            model_name='customer',
            name='liked',
            field=models.ManyToManyField(to='account.Vendor'),
        ),
    ]
