# Generated by Django 2.2.14 on 2020-10-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20201005_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='maintencefees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubHouseAvailable', models.IntegerField(blank=True, null=True)),
                ('GuestHouseAvailable', models.IntegerField(blank=True, null=True)),
                ('FunctionHall', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
    ]
