# Generated by Django 2.2.14 on 2020-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20201006_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Type',
            field=models.CharField(blank=True, choices=[('Club House', 'Club House'), ('Guest House', 'Guest House'), ('Function Hall', 'Function Hall')], max_length=200, null=True),
        ),
    ]
