# Generated by Django 2.2.14 on 2020-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_bookings_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
