# Generated by Django 2.2.14 on 2020-10-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20201006_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
