# Generated by Django 2.2.14 on 2020-10-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20201006_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ClubHouseAvailable',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='FunctionHall',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='GuestHouseAvailable',
        ),
    ]
