# Generated by Django 2.2.14 on 2020-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20201007_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='enddate',
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
