# Generated by Django 2.2.14 on 2020-10-07 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20201007_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=200, null=True),
        ),
    ]
