# Generated by Django 2.2.14 on 2020-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20201007_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='premium',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
