# Generated by Django 2.2.14 on 2020-10-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_customer_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='premium',
        ),
    ]
